import { ClientType } from '@/api/enums';

export interface IOrderFormValues {
  id?: number;
  application_id?: number | string;
  application_full_name?: string;
  sender_id?: number;
  receiver_id?: number;
  source_id?: number | string;
  delivery_type?: number | string;
  delivery_type_name?: string;
  delivery_category?: string;
  package_type?: number | string;
  package_type_name?: string;
  weight?: number | string;
  width?: number | string;
  length?: number | string;
  height?: number | string;
  volume?: number | string;
  nominal_cost?: number | string;
  is_express?: boolean;
  places_count?: number | string;
  customs_clearance?: boolean;
  price?: number | string;
  package_description?: string;
  special_wishes?: string;
  is_international?: boolean;
  status?: string;
  order_content?: string[];
  sender_first_name?: string;
  sender_last_name?: string;
  sender_patronymic?: string;
  sender_bin?: string;
  sender_type?: ClientType.INDIVIDUAL | ClientType.LEGAL;
  sender_company_name?: string;
  sender_country_id?: number | string;
  sender_country_name?: string;
  sender_city_id?: number | string;
  sender_city_name?: string;
  sender_phone?: string;
  sender_street?: string;
  sender_house?: string;
  sender_apartment?: string;
  sender_location_description?: string;
  sender_notes?: string;
  sender_contact_id?: number | null | string;
  receiver_first_name?: string;
  receiver_last_name?: string;
  receiver_patronymic?: string;
  receiver_bin?: string;
  receiver_type?: ClientType.INDIVIDUAL | ClientType.LEGAL;
  receiver_company_name?: string;
  receiver_country_id?: number | string;
  receiver_country_name?: string;
  receiver_city_id?: number | string;
  receiver_city_name?: string;
  receiver_phone?: string;
  receiver_street?: string;
  receiver_house?: string;
  receiver_apartment?: string;
  receiver_location_description?: string;
  receiver_notes?: string;
  receiver_contact_id?: number | null | string;
}
